### ISSUE TITLE
Add sample tables using knex migrations for the node-app-mssql example

### ISSUE THREAD

**Issue by kabirbaidhya** [leapfrogtechnology/sync-db#21]
Add sample tables for the [node-app-mssql](https://github.com/leapfrogtechnology/sync-db/tree/master/examples/node-app-mssql) example.

### What needs to be done?
- Put migrations (use [knex](http://knexjs.org/#Installation-migrations)) for creating sample tables under `examples/node-app-mssql/src/migrations`
- Add instructions for running migrations in the README
- Update the codebase such that output displays the list of tables you've created like this: 
   ![image](https://user-images.githubusercontent.com/3315763/67228552-35007580-f459-11e9-8e81-28f83fb49615.png)

**Comment by drwm-base** [comment]
Could I work on this?

**Comment by mesaugat** [comment]
Yes @drwm-base, go ahead. Let us know if you are not clear with the instructions.
