### ISSUE TITLE
Database objects not deleted from db when removed from sync-db.yml file.

### ISSUE THREAD

**Issue by silwalanish** [leapfrogtechnology/sync-db#224]
Database objects not deleted from db when removed from sync-db.yml file.

**Comment by mesaugat** [comment]
@silwalanish We already have a feature for this one. Just add `.drop` at the end of the filename in `sync-db.yml` object list.

Check here: https://github.com/leapfrogtechnology/sync-db/blob/master/examples/node-app-mssql/sync-db.yml#L15

You can remove the object filename from the `sync-db.yml` after you run sync-db once with `.drop` included.

Let me know if this solves your issue?

**Comment by silwalanish** [comment]
@mesaugat Cool. Let me test it. It should fix this issue.

**Comment by mesaugat** [comment]
@silwalanish Closing. Please re-open if you have have issues with the feature.
