### ISSUE TITLE
Add new example project based on postgres

### ISSUE THREAD

**Issue by kabirbaidhya** [leapfrogtechnology/sync-db#25]
Add new example project based on postgres.

**Requirements**
1. Add the sample project under `examples/node-app-pg`
2. Make it similar to the MSSQL example [here](https://github.com/leapfrogtechnology/sync-db/tree/master/examples/node-app-mssql) but use postgres insteaad of MSSQL.
3. Requires all the functionalities, docs, migrations like what the mssql example has.
4. Add the new example link under the main README [here](https://github.com/leapfrogtechnology/sync-db#examples)

**Comment by Prabeshpd** [comment]
I will work on it.

**Comment by kabirbaidhya** [comment]
Done in #35
