### ISSUE TITLE
Logs are misleading in rollback / teardown stage

### ISSUE THREAD

**Issue by SafalPandey** [leapfrogtechnology/sync-db#5]
## Issue

When the folder names where the database objects are in do not match one of `procedure`, `schema`, `view` or `function`, the logs explicitly say `Rolling back <object name>` and `Executed: <xx> ms` However the objects aren't removed from the database.

## Expected behavior

I think it should raise an error instead. We need to make it clear that the directory name did not match the expected convention and raise an error if rollback script is not executed.

## Log trail

```
  sync-db:db1 Synchronize database +0ms
  sync-db:db1 Running rollback on a database: db1 +0ms
  sync-db:db1 Rolling back: etl.noop +0ms
  sync-db:db1 Executed:   +48ms
  sync-db:db1 Rolling back: etl +0ms
  sync-db:db1 Executed:   +2ms
  sync-db:db1 Finished running rollback +273ms
  sync-db:db1 Running setup +0ms
  sync-db:db1 Running schemas/etl.sql +0ms
  sync-db:db1 Running procedures/etl/noop.sql +0ms
  sync-db Error caught:  { TransactionError: Transaction has been aborted.
...
```

**Comment by p0k8h** [comment]
I'll be working on this.
