### ISSUE TITLE
Get access to `setup` and `teardown` methods from cli

### ISSUE THREAD

**Issue by SafalPandey** [leapfrogtechnology/sync-db#9]
I have a use case where I need to run the `teardown` script again after `run` and `post_sync` scripts have completed.

I think we need to provide access to the `teardown` and `setup` steps independently as well.

Something like:
1. `teardown`
    ```bash
    # Rolls back all the db objects
    $ sync-db --teardown
    ```
2. `setup`
    ```bash
    # Creates all the db objects
    $ sync-db --setup
    ```
3. `setup`
    ```bash
    # Rolls back and Creates all the db objects
    $ sync-db
    ```

**Comment by kabirbaidhya** [comment]
@SafalPandey We have the ability to use programmatic API now and this use case can be addressed with it. Let's close this one.
