### ISSUE TITLE
Add examples and update documentation for JS/TS migrations and dry-run command

### ISSUE THREAD

**Issue by mesaugat** [leapfrogtechnology/sync-db#90]
JS/TS knex migration support was recently added. #88 

Include examples of JS/TS migrations with sync-db.

**Comment by kabirbaidhya** [comment]
Need to update the documentation as well. The README text is sort of outdated.

**Comment by mesaugat** [comment]
Yes, I was about to create an issue for that too. @kabirbaidhya

**Comment by cham11ng** [comment]
Here's the PR for this. https://github.com/leapfrogtechnology/sync-db/pull/100

**Comment by mesaugat** [comment]
Closed by #100
